### ISSUE TITLE
gemspec "gem build" problems

### ISSUE THREAD

**Issue by leamas** [collectiveidea/devise-mongo_mapper#1]
Im really a ruby newbie and might have got it all wrong, but still:

In the diaspora project, I've lately experienced errors when building this gem:
    ERROR:  While executing gem ... (Gem::InvalidSpecificationException)
    ["README.md"] are not files

Patching gemspec file to look like 
      s.files         = Dir.glob('lib/*_/_') + Dir.glob('README.md')

Although this is certainly silly, it works and I can build the gem. Using Ruby 1.8.7. 

Feeling dumb, this has worked for some time in diaspora, and I have no idea what's changed.

**Comment by leamas** [comment]
Maybe this is not enterily my bad, seem to be related to https://github.com/igrigorik/em-websocket/issues/closed#issue/18

**Comment by asheren** [comment]
Hi there! We're doing some open source maintenance work and closing old issues. If this issue is still applicable or you would still like it to be addressed, please re-open the issue by April 17, 2017. Thanks!
