### ISSUE TITLE
Devise 1.3.3

### ISSUE THREAD

**Issue by addynaik** [collectiveidea/devise-mongo_mapper#3]
Any reason why this cannot use devise 1.3.3. currently the gem requires <~1.1

**Comment by Sedward** [comment]
I'm wondering the same thing

**Comment by asheren** [comment]
Hi there! We're doing some open source maintenance work and closing old issues. If this issue is still applicable or you would still like it to be addressed, please re-open the issue by April 17, 2017. Thanks!
